# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KadaiApp2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KadaiApp2
  pod 'FluctSDK'

  target 'KadaiApp2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KadaiApp2UITests' do
    # Pods for testing
  end

end
